# Generated by Django 3.0.7 on 2022-11-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20221114_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReportStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='notificationstaffs',
            old_name='stafff_id',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='teacher_id',
            new_name='staff_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Adminn'), (2, 'Staff'), (3, 'Student')], default=1, max_length=10),
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Staffs',
        ),
        migrations.DeleteModel(
            name='LeaveReportTeacher',
        ),
        migrations.AddField(
            model_name='leavereportstaff',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Staffs'),
        ),
    ]
