# Generated by Django 3.0.7 on 2022-11-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_auto_20221115_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
