# Generated by Django 3.0.7 on 2022-11-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.SessionYearModel'),
            preserve_default=False,
        ),
    ]
