# Generated by Django 3.0.7 on 2022-11-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_auto_20221116_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.Courses'),
        ),
    ]
