# Generated by Django 3.0.7 on 2022-11-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_students_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
    ]
