# Generated by Django 3.0.7 on 2022-11-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_remove_students_session_year_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
    ]
