# Generated by Django 3.0.7 on 2022-11-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_auto_20221116_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='admin',
            field=models.TextField(),
        ),
    ]
