CREATE DATABASE BLOOD_MANAGEMENT_SYSTEM;

ALTER DATABASE BLOOD_MANAGEMENT_SYSTEM 
COLLATE Cyrillic_General_CI_AS

USE BLOOD_MANAGEMENT_SYSTEM;

CREATE TABLE REGION(
REGION_ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
)

CREATE TABLE CITY(
CITY_ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
REGION_ID INT FOREIGN KEY (REGION_ID) REFERENCES REGION
)

CREATE TABLE HOSPITAL(
HOSPITAL_ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(60) NOT NULL,
ADDRESS VARCHAR(70) NOT NULL,
CITY_ID INTEGER FOREIGN KEY (CITY_ID) REFERENCES CITY,
PHONE_NUMBER VARCHAR (10) NOT NULL,
WEBSITE TEXT,
EMAIL VARCHAR(30)
)

CREATE TABLE BLOOD(
BLOOD_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
BLOOD_GROUP VARCHAR(3) NOT NULL,
QUANTITY DECIMAL NOT NULL
)


CREATE TABLE BLOOD_BANK(
BANK_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(70) NOT NULL,
CITY_ID INT FOREIGN KEY (CITY_ID) REFERENCES CITY ON DELETE CASCADE,
ADDRESS VARCHAR (50) NOT NULL,
WEBSITE TEXT,
PHONE VARCHAR(10) NOT NULL,
BLOOD_ID INT FOREIGN KEY (BLOOD_ID) REFERENCES BLOOD
)

CREATE TABLE DONOR(
DONOR_ID INT PRIMARY KEY IDENTITY(1,1),
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
BLOOD_GROUP CHAR(3) NOT NULL,
PHONE VARCHAR(10) NOT NULL,
CITY_ID INT FOREIGN KEY (CITY_ID) REFERENCES CITY,
ADDRESS TEXT
)

CREATE TABLE DONOR_CARD(
CARD_ID INT PRIMARY KEY IDENTITY(1,1),
DONOR_ID INT FOREIGN KEY (DONOR_ID) REFERENCES DONOR,
DATE DATETIME NOT NULL,
QUANTITY NUMERIC(6,3) NOT NULL
)

CREATE TABLE REQUEST(
ID INT PRIMARY KEY IDENTITY(1,1),
DATE DATETIME NOT NULL,
HOSPITAL_ID INT FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL,
QUANTITY NUMERIC(6,3) NOT NULL,
BLOOD_GROUP CHAR(3) NOT NULL
)


INSERT INTO REGION VALUES
(1,'Югозападен'),
(2,'Северозападен'),
(3,'Северен централен'),
(4,'Североизточен'),
(5,'Югоизточен'),
(6,'Южен централен')

INSERT INTO CITY VALUES
(1,'Видин',2),
(1,'Видин',2)