CREATE DATABASE TEST

CREATE TABLE CLIENTS(
CLIENT_ID INT PRIMARY KEY NOT NULL,
FNAME VARCHAR(15) NOT NULL,
LNAME VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(50) NULL
)

CREATE TABLE MEDIA(
MEDIA_ID CHAR(5) PRIMARY KEY NOT NULL,
TITLE VARCHAR(30) NOT NULL,
CREATED DATETIME NOT NULL
)

CREATE TABLE CLIENTSMEDIA(
CLIENT_ID INT NOT NULL FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS,
MEDIA_ID CHAR(5) NOT NULL FOREIGN KEY (MEDIA_ID) REFERENCES MEDIA,
DATERENT DATETIME NOT NULL,
PRICE DECIMAL(6,2) NULL,
PRIMARY KEY(CLIENT_ID,MEDIA_ID)
)

INSERT INTO CLIENTS VALUES (1,'Erika','Karamucheva','Plovdiv')
INSERT INTO CLIENTS VALUES (46,'Veronika','Georgieva','Sofia')
INSERT INTO MEDIA VALUES (1,'TITANIC','2017-07-03')
INSERT INTO CLIENTSMEDIA VALUES(1,1,'2019-04-29',24.5)

UPDATE CLIENTS
SET ADDRESS='Asenvgrad'
WHERE CLIENT_ID=46

SELECT FNAME, LNAME FROM CLIENTS

SELECT TITLE 
FROM CLIENTSMEDIA JOIN MEDIA 
ON MEDIA.MEDIA_ID=CLIENTSMEDIA.MEDIA_ID
WHERE PRICE>5.0

CREATE TABLE SUPPLIERS(
SID CHAR(8) PRIMARY KEY NOT NULL,
NAME VARCHAR(30) NOT NULL,
CITY VARCHAR(20) NULL
)

CREATE TABLE PARTS(
PART_ID INT PRIMARY KEY NOT NULL,
PART_NAME VARCHAR(30) NOT NULL,
COLOR VARCHAR(10) NULL,
WEIGHT DECIMAL(6,3) NULL
)

CREATE TABLE SUPPLIES_PARTS(
SID CHAR(8) NOT NULL FOREIGN KEY (SID) REFERENCES SUPPLIERS,
PART_ID INT NOT NULL FOREIGN KEY (PART_ID) REFERENCES PARTS,
QUANTITY INT NOT NULL,
PRIMARY KEY (SID,PART_ID)
)

INSERT INTO SUPPLIERS VALUES ('SPD','SPEEDY','PLOVDIV')
INSERT INTO PARTS VALUES(3,'NOTEBOOK','GREY',0.4)
INSERT INTO SUPPLIES_PARTS VALUES('SPD',3,14)


--DELETE SUPPLIERS_PARTS, PARTS 
--WHERE WEIGHT<50

SELECT COLOR, PART_NAME FROM PARTS

SELECT PART_NAME FROM PARTS JOIN SUPPLIES_PARTS
ON SUPPLIES_PARTS.PART_ID=PARTS.PART_ID
WHERE QUANTITY>100
